/*
 * This source file was generated by the Gradle 'init' task
 */
package com.pucmm.network;
import com.pucmm.network.*;
import com.pucmm.network.topologia.BusNetwork;;

public class Main {
    public static void main(String[] args) {
        // Crear una instancia de NetworkManager
        NetworkManager manager = new NetworkMannager();

        // Configurrar la red con la topologia de bus y otros parametros necesarios
        manager.configureNetwork(New BusNetwork());

        // Ejecutar la red
        manager.runNetwork();

    }
}
