/*
 * This source file was generated by the Gradle 'init' task
 */
package practica_2;

import org.junit.jupiter.api.Test;

import com.pucmm.network.Main;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        Main classUnderTest = new Main();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
